config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/packages')

  resources :packages, only: [:index] do
    resources :versions, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :latest_version, class_name: "Version"
  has_many :versions
end

app/models/version.rb
class Version < ApplicationRecord
  belongs_to :package

  validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def index
    @packages = Package.includes(:latest_version).order("LOWER(name)").all
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def show
    @package = Package.find(params[:package_id])
    @version = Version.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RProjectPackages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/versions/show.html.erb
<h1 class="mt-3"><%= @package.name %> (<%= @version.number %>)</h1>

<h4 class="text-secondary"><%= @version.title %></h4>

<p><%= @version.description %></p>

<span class="text-muted small">Publication date: <%= @version.date_publication %></span><br>
<span class="text-muted small">Author: <%= @version.author %></span><br>
<span class="text-muted small">Maintainers: <%= @version.maintainers %></span><br>

<h4 class="mt-3">All versions:</h4>
<ul>
  <% @package.versions.each do |version| %>
    <li><%= link_to version.number, package_version_path(@package, version) %></li>
  <% end %>
</ul>